### ISSUE TITLE
Migrate to Javascript from coffee?

### ISSUE THREAD

**Issue by radum** [itsthatguy/gridwax#17]
Would you consider migrating the code to pure Javascript rather than coffee?

I could help with a PR.

**Comment by TylerK** [comment]
+1 ;)

**Comment by itsthatguy** [comment]
No.

**Comment by itsthatguy** [comment]
Version 1 was written in javascript, Version 2 featured an intentional migration to coffeescript.

https://github.com/itsthatguy/gridwax/commit/d56ebd076a798e149f7ee118f40e193eff73a760
