### ISSUE TITLE
Uncaught TypeError: boolean is not a function gridwax.js:16

### ISSUE THREAD

**Issue by drewish** [itsthatguy/gridwax#9]
The positioning of everything was screwy and the lineheight would only get smaller so I popped open Chrome 29.0.1547.65's inspector and noticed the JS error in the subject.

**Comment by radum** [comment]
I tried also, and I can't reproduce. @drewish

**Comment by drewish** [comment]
Sure I haven't been using it. If no one else is seeing it must have been a quirk.
